import math
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.distributed.nn
from torch.autograd import Variable
def _no_grad_trunc_normal_(tensor, mean, std, a, b):
    # Cut & paste from PyTorch official master until it's in a few official releases - RW
    # Method based on https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf
    def norm_cdf(x):
        # Computes standard normal cumulative distribution function
        return (1. + math.erf(x / math.sqrt(2.))) / 2.

    if (mean < a - 2 * std) or (mean > b + 2 * std):
        print("mean is more than 2 std from [a, b] in nn.init.trunc_normal_. "
                      "The distribution of values may be incorrect.",)

    with torch.no_grad():
        # Values are generated by using a truncated uniform distribution and
        # then using the inverse CDF for the normal distribution.
        # Get upper and lower cdf values
        l = norm_cdf((a - mean) / std)
        u = norm_cdf((b - mean) / std)

        # Uniformly fill tensor with values from [l, u], then translate to
        # [2l-1, 2u-1].
        tensor.uniform_(2 * l - 1, 2 * u - 1)

        # Use inverse cdf transform for normal distribution to get truncated
        # standard normal
        tensor.erfinv_()

        # Transform to proper mean, std
        tensor.mul_(std * math.sqrt(2.))
        tensor.add_(mean)

        # Clamp to ensure it's in the proper range
        tensor.clamp_(min=a, max=b)
        return tensor


def trunc_normal_(tensor, mean=0., std=1., a=-2., b=2.):
    # type: (Tensor, float, float, float, float) -> Tensor
    r"""Fills the input Tensor with values drawn from a truncated
    normal distribution. The values are effectively drawn from the
    normal distribution :math:`\mathcal{N}(\text{mean}, \text{std}^2)`
    with values outside :math:`[a, b]` redrawn until they are within
    the bounds. The method used for generating the random values works
    best when :math:`a \leq \text{mean} \leq b`.
    Args:
        tensor: an n-dimensional `torch.Tensor`
        mean: the mean of the normal distribution
        std: the standard deviation of the normal distribution
        a: the minimum cutoff value
        b: the maximum cutoff value
    Examples:
        >>> w = torch.empty(3, 5)
        >>> nn.init.trunc_normal_(w)
    """
    return _no_grad_trunc_normal_(tensor, mean, std, a, b)



# class blocks_InfoNCE(nn.Module):

#     def __init__(self, loss_function, device='cuda' if torch.cuda.is_available() else 'cpu'):
#         super().__init__()
#         self.loss_function = loss_function
#         self.device = device

#     def forward(self, image_features1, image_features2, logit_scale):


#         # 1. concate
#         if 1:
#             channels1 = [image_features1[:, :, i] for i in range(image_features1.shape[2])]
#             channels2 = [image_features2[:, :, i] for i in range(image_features2.shape[2])]

#             # 使用 torch.cat 连接所有通道
#             image_features_blocks_1 = torch.cat(channels1, dim=-1)
#             image_features_blocks_2 = torch.cat(channels2, dim=-1)

#             image_features1 = F.normalize(image_features_blocks_1, dim=-1)
#             image_features2 = F.normalize(image_features_blocks_2, dim=-1)

#             logits_per_image1 = logit_scale * image_features1 @ image_features2.T

#             logits_per_image2 = logits_per_image1.T

#             labels = torch.arange(len(logits_per_image1), dtype=torch.long, device=self.device)

#             loss = (self.loss_function(logits_per_image1, labels) + self.loss_function(logits_per_image2, labels)) / 2


#         return loss





class blocks_InfoNCE(nn.Module):
    def __init__(self, loss_function, device='cuda' if torch.cuda.is_available() else 'cpu'):
        super().__init__()
        self.loss_function = loss_function
        self.device = device

    def forward(self, image_features1, image_features2, logit_scale):
        num_blocks = image_features1.shape[2]
        loss = 0

        for i in range(num_blocks):
            # 单独提取第 i 个块的特征
            block1 = F.normalize(image_features1[:, :, i], dim=-1)
            block2 = F.normalize(image_features2[:, :, i], dim=-1)

            # 计算该块的对比 logits
            logits_per_image = logit_scale * block1 @ block2.T
            labels = torch.arange(len(logits_per_image), dtype=torch.long, device=self.device)

            # 累加逐块 InfoNCE 损失
            loss += self.loss_function(logits_per_image, labels)

        # 平均每个块的损失
        loss = loss / num_blocks
        return loss

